export interface Category {
  id: string;
  name: string;
  display_order: number;
}

export interface Product {
  id: string;
  category_id: string;
  name: string;
  description: string | null;
  price: number;
  image_url: string | null;
  available: boolean;
  ingredients: string[] | null;
  allergens: string[] | null;
}

export interface ProductOption {
  id: string;
  product_id: string;
  option_type: 'size' | 'meat' | 'sauce' | 'supplement';
  name: string;
  price: number;
}

export interface CartItem {
  product: Product;
  quantity: number;
  selectedOptions?: {
    size?: ProductOption;
    meats?: ProductOption[];
    sauces?: ProductOption[];
    supplements?: ProductOption[];
  };
  totalPrice: number;
}

export const categories: Category[] = [
  { id: '1', name: 'Menu Étudiant', display_order: 1 },
  { id: '2', name: 'Tacos', display_order: 2 },
  { id: '3', name: 'Burgers', display_order: 3 },
  { id: '4', name: 'Paninis', display_order: 4 },
  { id: '5', name: 'Salades', display_order: 5 },
  { id: '6', name: 'Accompagnements', display_order: 6 },
  { id: '7', name: 'Desserts', display_order: 7 },
  { id: '8', name: 'Boissons', display_order: 8 },
];

export const products: Product[] = [
  {
    id: 'p1',
    category_id: '1',
    name: 'Menu Étudiant Tacos',
    description: 'Tacos + Frites + Boisson',
    price: 8.90,
    image_url: null,
    available: true,
    ingredients: ['Galette de blé', 'Viande au choix', 'Fromage', 'Sauce au choix', 'Salade', 'Tomate', 'Oignon', 'Pommes de terre', 'Boisson'],
    allergens: ['Gluten', 'Lactose', 'Peut contenir des traces de fruits à coque'],
  },
  {
    id: 'p2',
    category_id: '1',
    name: 'Menu Étudiant Burger',
    description: 'Burger + Frites + Boisson',
    price: 8.90,
    image_url: null,
    available: true,
    ingredients: ['Pain burger', 'Steak haché', 'Fromage', 'Salade', 'Tomate', 'Oignon', 'Sauce', 'Pommes de terre', 'Boisson'],
    allergens: ['Gluten', 'Lactose', 'Œuf', 'Peut contenir des traces de fruits à coque'],
  },
  {
    id: 'p3',
    category_id: '1',
    name: 'Menu Étudiant Panini',
    description: 'Panini + Frites + Boisson',
    price: 8.90,
    image_url: null,
    available: true,
    ingredients: ['Pain panini', 'Garniture au choix', 'Fromage', 'Pommes de terre', 'Boisson'],
    allergens: ['Gluten', 'Lactose'],
  },
  {
    id: 't1',
    category_id: '2',
    name: 'Tacos S',
    description: '1 viande au choix',
    price: 6.00,
    image_url: null,
    available: true,
    ingredients: ['Galette de blé', '1 viande au choix', 'Fromage', 'Sauce au choix', 'Salade', 'Tomate', 'Oignon'],
    allergens: ['Gluten', 'Lactose', 'Peut contenir des traces de fruits à coque'],
  },
  {
    id: 't2',
    category_id: '2',
    name: 'Tacos M',
    description: '2 viandes au choix',
    price: 7.50,
    image_url: null,
    available: true,
    ingredients: ['Galette de blé', '2 viandes au choix', 'Fromage', 'Sauce au choix', 'Salade', 'Tomate', 'Oignon'],
    allergens: ['Gluten', 'Lactose', 'Peut contenir des traces de fruits à coque'],
  },
  {
    id: 't3',
    category_id: '2',
    name: 'Tacos L',
    description: '3 viandes au choix',
    price: 9.00,
    image_url: null,
    available: true,
    ingredients: ['Galette de blé', '3 viandes au choix', 'Fromage', 'Sauce au choix', 'Salade', 'Tomate', 'Oignon'],
    allergens: ['Gluten', 'Lactose', 'Peut contenir des traces de fruits à coque'],
  },
  {
    id: 't4',
    category_id: '2',
    name: 'Tacos XL',
    description: '4 viandes au choix',
    price: 10.50,
    image_url: null,
    available: true,
    ingredients: ['Galette de blé', '4 viandes au choix', 'Fromage', 'Sauce au choix', 'Salade', 'Tomate', 'Oignon'],
    allergens: ['Gluten', 'Lactose', 'Peut contenir des traces de fruits à coque'],
  },
  {
    id: 't5',
    category_id: '2',
    name: 'Tacos Personnalisé',
    description: 'Créez votre tacos sur mesure',
    price: 6.00,
    image_url: null,
    available: true,
    ingredients: ['Galette de blé', 'Viandes au choix', 'Fromage', 'Sauces au choix', 'Légumes au choix', 'Suppléments optionnels'],
    allergens: ['Gluten', 'Lactose', 'Peut contenir des traces de fruits à coque', 'Œuf'],
  },
  {
    id: 'b1',
    category_id: '3',
    name: 'Burger Classique',
    description: 'Steak haché, salade, tomate, oignon',
    price: 6.50,
    image_url: null,
    available: true,
    ingredients: ['Pain burger', 'Steak haché', 'Salade', 'Tomate', 'Oignon', 'Sauce'],
    allergens: ['Gluten', 'Œuf'],
  },
  {
    id: 'b2',
    category_id: '3',
    name: 'Cheeseburger',
    description: 'Steak haché, fromage, salade, tomate',
    price: 7.00,
    image_url: null,
    available: true,
    ingredients: ['Pain burger', 'Steak haché', 'Fromage', 'Salade', 'Tomate', 'Sauce'],
    allergens: ['Gluten', 'Lactose', 'Œuf'],
  },
  {
    id: 'b3',
    category_id: '3',
    name: 'Burger Chicken',
    description: 'Poulet pané, salade, tomate, mayo',
    price: 7.00,
    image_url: null,
    available: true,
    ingredients: ['Pain burger', 'Poulet pané', 'Salade', 'Tomate', 'Mayonnaise'],
    allergens: ['Gluten', 'Œuf'],
  },
  {
    id: 'b4',
    category_id: '3',
    name: 'Burger Kebab',
    description: 'Viande kebab, salade, tomate, oignon',
    price: 7.50,
    image_url: null,
    available: true,
    ingredients: ['Pain burger', 'Viande kebab', 'Salade', 'Tomate', 'Oignon', 'Sauce'],
    allergens: ['Gluten', 'Œuf'],
  },
  {
    id: 'pan1',
    category_id: '4',
    name: 'Panini Poulet',
    description: 'Poulet, fromage, sauce',
    price: 5.50,
    image_url: null,
    available: true,
    ingredients: ['Pain panini', 'Poulet', 'Fromage', 'Sauce'],
    allergens: ['Gluten', 'Lactose'],
  },
  {
    id: 'pan2',
    category_id: '4',
    name: 'Panini Thon',
    description: 'Thon, fromage, sauce',
    price: 5.50,
    image_url: null,
    available: true,
    ingredients: ['Pain panini', 'Thon', 'Fromage', 'Sauce'],
    allergens: ['Gluten', 'Lactose', 'Poisson'],
  },
  {
    id: 'pan3',
    category_id: '4',
    name: 'Panini Kebab',
    description: 'Viande kebab, fromage, sauce',
    price: 5.50,
    image_url: null,
    available: true,
    ingredients: ['Pain panini', 'Viande kebab', 'Fromage', 'Sauce'],
    allergens: ['Gluten', 'Lactose'],
  },
  {
    id: 's1',
    category_id: '5',
    name: 'Salade César',
    description: 'Poulet, parmesan, croutons, sauce césar',
    price: 7.50,
    image_url: null,
    available: true,
    ingredients: ['Salade verte', 'Poulet grillé', 'Parmesan', 'Croutons', 'Sauce césar'],
    allergens: ['Gluten', 'Lactose', 'Œuf', 'Poisson'],
  },
  {
    id: 's2',
    category_id: '5',
    name: 'Salade Composée',
    description: 'Thon, œuf, tomate, concombre',
    price: 7.00,
    image_url: null,
    available: true,
    ingredients: ['Salade verte', 'Thon', 'Œuf dur', 'Tomate', 'Concombre', 'Olives', 'Vinaigrette'],
    allergens: ['Œuf', 'Poisson'],
  },
  {
    id: 'a1',
    category_id: '6',
    name: 'Frites',
    description: 'Portion de frites maison',
    price: 3.00,
    image_url: null,
    available: true,
    ingredients: ['Pommes de terre', 'Huile végétale', 'Sel'],
    allergens: ['Peut contenir des traces de gluten'],
  },
  {
    id: 'a2',
    category_id: '6',
    name: 'Nuggets (6 pcs)',
    description: '6 nuggets de poulet croustillants',
    price: 4.50,
    image_url: null,
    available: true,
    ingredients: ['Poulet', 'Panure (farine de blé, épices)', 'Huile végétale'],
    allergens: ['Gluten', 'Peut contenir des traces de lactose et œuf'],
  },
  {
    id: 'a3',
    category_id: '6',
    name: 'Onion Rings',
    description: 'Rondelles d\'oignons panées',
    price: 4.00,
    image_url: null,
    available: true,
    ingredients: ['Oignon', 'Panure (farine de blé, épices)', 'Huile végétale'],
    allergens: ['Gluten', 'Peut contenir des traces de lactose et œuf'],
  },
  {
    id: 'a4',
    category_id: '6',
    name: 'Cheese Sticks',
    description: 'Bâtonnets de fromage panés',
    price: 4.50,
    image_url: null,
    available: true,
    ingredients: ['Fromage mozzarella', 'Panure (farine de blé, épices)', 'Huile végétale'],
    allergens: ['Gluten', 'Lactose', 'Peut contenir des traces d\'œuf'],
  },
  {
    id: 'a5',
    category_id: '6',
    name: 'Potatoes',
    description: 'Quartiers de pommes de terre épicés',
    price: 3.50,
    image_url: null,
    available: true,
    ingredients: ['Pommes de terre', 'Épices', 'Huile végétale'],
    allergens: ['Peut contenir des traces de gluten'],
  },
  {
    id: 'd1',
    category_id: '7',
    name: 'Tiramisu',
    description: 'Dessert italien traditionnel',
    price: 3.50,
    image_url: null,
    available: true,
    ingredients: ['Mascarpone', 'Biscuits', 'Café', 'Cacao'],
    allergens: ['Gluten', 'Lactose', 'Œuf'],
  },
  {
    id: 'd2',
    category_id: '7',
    name: 'Brownie',
    description: 'Gâteau au chocolat fondant',
    price: 3.00,
    image_url: null,
    available: true,
    ingredients: ['Chocolat', 'Farine', 'Beurre', 'Sucre', 'Œufs'],
    allergens: ['Gluten', 'Lactose', 'Œuf', 'Peut contenir des traces de fruits à coque'],
  },
  {
    id: 'd3',
    category_id: '7',
    name: 'Moelleux au Chocolat',
    description: 'Coulant au chocolat',
    price: 3.50,
    image_url: null,
    available: true,
    ingredients: ['Chocolat', 'Farine', 'Beurre', 'Sucre', 'Œufs'],
    allergens: ['Gluten', 'Lactose', 'Œuf'],
  },
  {
    id: 'dr1',
    category_id: '8',
    name: 'Coca-Cola 33cl',
    description: 'Canette 33cl',
    price: 2.00,
    image_url: null,
    available: true,
    ingredients: ['Eau gazéifiée', 'Sucre', 'Colorant E150d', 'Acidifiant', 'Arômes naturels', 'Caféine'],
    allergens: ['Sans allergènes majeurs'],
  },
  {
    id: 'dr2',
    category_id: '8',
    name: 'Coca-Cola Zero 33cl',
    description: 'Canette 33cl',
    price: 2.00,
    image_url: null,
    available: true,
    ingredients: ['Eau gazéifiée', 'Colorant E150d', 'Acidifiant', 'Édulcorants', 'Arômes naturels', 'Caféine'],
    allergens: ['Contient une source de phénylalanine'],
  },
  {
    id: 'dr3',
    category_id: '8',
    name: 'Fanta Orange 33cl',
    description: 'Canette 33cl',
    price: 2.00,
    image_url: null,
    available: true,
    ingredients: ['Eau gazéifiée', 'Sucre', 'Jus d\'orange (5%)', 'Acidifiant', 'Arômes naturels'],
    allergens: ['Sans allergènes majeurs'],
  },
  {
    id: 'dr4',
    category_id: '8',
    name: 'Sprite 33cl',
    description: 'Canette 33cl',
    price: 2.00,
    image_url: null,
    available: true,
    ingredients: ['Eau gazéifiée', 'Sucre', 'Acidifiant', 'Arômes naturels'],
    allergens: ['Sans allergènes majeurs'],
  },
  {
    id: 'dr5',
    category_id: '8',
    name: 'Ice Tea 33cl',
    description: 'Canette 33cl',
    price: 2.00,
    image_url: null,
    available: true,
    ingredients: ['Eau', 'Sucre', 'Extrait de thé', 'Jus de citron', 'Acidifiant', 'Arômes naturels'],
    allergens: ['Sans allergènes majeurs'],
  },
  {
    id: 'dr6',
    category_id: '8',
    name: 'Eau Minérale 50cl',
    description: 'Bouteille 50cl',
    price: 1.50,
    image_url: null,
    available: true,
    ingredients: ['Eau minérale naturelle'],
    allergens: ['Sans allergènes'],
  },
  {
    id: 'dr7',
    category_id: '8',
    name: 'Oasis Tropical 33cl',
    description: 'Canette 33cl',
    price: 2.00,
    image_url: null,
    available: true,
    ingredients: ['Eau', 'Sucre', 'Jus de fruits', 'Acidifiant', 'Arômes naturels'],
    allergens: ['Sans allergènes majeurs'],
  },
];

export const productOptions: ProductOption[] = [
  { id: 'o1', product_id: 't5', option_type: 'size', name: 'S (1 viande)', price: 0.00 },
  { id: 'o2', product_id: 't5', option_type: 'size', name: 'M (2 viandes)', price: 1.50 },
  { id: 'o3', product_id: 't5', option_type: 'size', name: 'L (3 viandes)', price: 3.00 },
  { id: 'o4', product_id: 't5', option_type: 'size', name: 'XL (4 viandes)', price: 4.50 },

  { id: 'o5', product_id: 't5', option_type: 'meat', name: 'Poulet', price: 0.00 },
  { id: 'o6', product_id: 't5', option_type: 'meat', name: 'Bœuf', price: 0.00 },
  { id: 'o7', product_id: 't5', option_type: 'meat', name: 'Kebab', price: 0.00 },
  { id: 'o8', product_id: 't5', option_type: 'meat', name: 'Merguez', price: 0.00 },
  { id: 'o9', product_id: 't5', option_type: 'meat', name: 'Cordon Bleu', price: 0.00 },
  { id: 'o10', product_id: 't5', option_type: 'meat', name: 'Steak Haché', price: 0.00 },

  { id: 'o11', product_id: 't5', option_type: 'sauce', name: 'Blanche', price: 0.00 },
  { id: 'o12', product_id: 't5', option_type: 'sauce', name: 'Harissa', price: 0.00 },
  { id: 'o13', product_id: 't5', option_type: 'sauce', name: 'Algérienne', price: 0.00 },
  { id: 'o14', product_id: 't5', option_type: 'sauce', name: 'Barbecue', price: 0.00 },
  { id: 'o15', product_id: 't5', option_type: 'sauce', name: 'Ketchup', price: 0.00 },
  { id: 'o16', product_id: 't5', option_type: 'sauce', name: 'Mayonnaise', price: 0.00 },
  { id: 'o17', product_id: 't5', option_type: 'sauce', name: 'Samouraï', price: 0.00 },

  { id: 'o18', product_id: 't5', option_type: 'supplement', name: 'Supplément Frites', price: 1.00 },
  { id: 'o19', product_id: 't5', option_type: 'supplement', name: 'Supplément Fromage', price: 1.00 },
  { id: 'o20', product_id: 't5', option_type: 'supplement', name: 'Supplément Œuf', price: 0.50 },
  { id: 'o21', product_id: 't5', option_type: 'supplement', name: 'Supplément Légumes', price: 0.50 },
];
